### ISSUE TITLE
Http_proxy environment variable adding /n to Http-proxy.conf file

### ISSUE THREAD

**Issue by paul-weatherbee** [Mirantis/launchpad_legacy#34]
Using launchpad version 0.12.1 when I add a http_proxy environment variable to a host during the install it adds a /n to the Http-proxy.conf file.

I have run dos2unix on the cluster.yaml file to make sure it unix format and have run launchpad from MacOS and Linux.  

This is on a Ubuntu 18.04.4 system

**Comment by jakolehm** [comment]
This will be fixed in a next patch release.

**Comment by jakolehm** [comment]
Should be fixed in 0.12.2.

**Comment by 53d117460ec63d70** [comment]
Still seeing this issue in version 1.0.0:
```
$ launchpad version
version: 1.0.0-rc1
commit: c3f0a0b
```
Target host is CentOS 7
